name: shimmer_ai
description: >
  Effortless shimmer effects and skeleton loaders for Flutter widgets using `.withShimmerAi()` — smooth, customizable, and dependency-free.

version: 1.2.0
homepage: https://github.com/karanpadaliya/shimmer_ai
repository: https://github.com/karanpadaliya/shimmer_ai
issue_tracker: https://github.com/karanpadaliya/shimmer_ai/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - shimmer
  - skeleton-loader
  - loading-animation
  - flutter-ui
  - ux
