name: shimmer_ai
description: >
  A powerful Flutter package that provides zero-configuration shimmer loading placeholders.
  Easily add smooth, dynamic shimmer effects to any widget—Text, Container, ListTile, and more—
  with a simple one-line extension method `.withShimmerAi()`. Perfect for creating
  skeleton loaders, loading states, and polished user experiences.

version: 1.1.0
homepage: https://github.com/karanpadaliya/shimmer_ai
repository: https://github.com/karanpadaliya/shimmer_ai
issue_tracker: https://github.com/karanpadaliya/shimmer_ai/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - flutter
  - shimmer
  - skeleton-loader
  - loading-animation
  - flutter-ui

