name: shimmer_ai
description: >
  A powerful package, zero-config shimmer wrapper for Flutter. 
  Instantly shimmer any widget like Text, Container, or ListTile with one line using .withShimmerAi().
version: 1.0.0
homepage: https://github.com/your_github_username/shimmer_ai
repository: https://github.com/your_github_username/shimmer_ai
issue_tracker: https://github.com/your_github_username/shimmer_ai/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - flutter
  - shimmer
  - loading-animation
  - skeleton-loader
  - flutter-ui
